=== Manjunath-Aloji/mercury-scripts/model.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "name": { "type": "string" },
    "label": { "type": "string" },
    "description": { "type": "string" },
    "recordKey": { "type": "string" },
    "managed": { "type": "boolean" },
    "fields": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": { "type": "string" },
          "label": { "type": "string" },
          "type": {
            "type": "string",
            "enum": [
              "string",
              "number",
              "boolean",
              "date",
              "float",
              "virtual",
              "enum",
              "relationship"
            ]
          },
          "enumType": { "type": ["number", "string"] },
          "enumValues": {
            "type": "array",
            "items": { "type": "string" }
          },
          "managed": { "type": "boolean" },
          "many": { "type": "boolean" },
          "ref": { "type": "string" },
          "localField": { "type": "string" },
          "foreignField": { "type": "string" },
          "managedBy": { "type": "string" },
          "default": { "type": "string" },
          "immutable": { "type": "boolean" },
          "required": { "type": "boolean" },
          "unique": { "type": "boolean" }
        },
        "required": ["name", "label", "type"]
      }
    }
  },
  "required": ["name", "label"]
}

=== Manjunath-Aloji/mercury-scripts/user-model.json
{
    "$schema": "./model.schema.json",
    "name": "User",
    "label": "User",
    "description": "User model",
    "fields": [
        {
            "name": "first_name",
            "label": "first_name",
            "type": "string"
        },
        {
            "name": "last_name",
            "label": "last_name",
            "type": "string"
        }
    ]
}

=== Manjunath-Aloji/mercury-scripts/class-model.json
{
    "$schema": "./model.schema.json",
    "name": "Class",
    "label": "Class",
    "description": "Class model",
    "fields": [
        {
            "name": "name",
            "label": "name",
            "type": "string"
        },
        {
            "name": "description",
            "label": "description",
            "type": "string"
        },
        {
            "name": "institute",
            "label": "institute",
            "type": "relationship",
            "ref": "Institute"
        }
    ]
}
