=== Manjunath-Aloji/mercury-scripts/models/01-model.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "name": { "type": "string" },
    "label": { "type": "string" },
    "description": { "type": "string" },
    "recordKey": { "type": "string" },
    "managed": { "type": "boolean" },
    "fields": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": { "type": "string" },
          "label": { "type": "string" },
          "type": {
            "type": "string",
            "enum": [
              "string",
              "number",
              "boolean",
              "date",
              "float",
              "virtual",
              "enum",
              "relationship"
            ]
          },
          "enumType": { "type": "string", "enum": ["number", "string"] },
          "enumValues": {
            "type": "array",
            "items": { "type": "string" }
          },
          "managed": { "type": "boolean" },
          "many": { "type": "boolean" },
          "ref": { "type": "string" },
          "localField": { "type": "string" },
          "foreignField": { "type": "string" },
          "managedBy": { "type": "string" },
          "default": { "type": ["string", "boolean"] },
          "immutable": { "type": "boolean" },
          "required": { "type": "boolean" },
          "unique": { "type": "boolean" }
        },
        "required": ["name", "label", "type"]
      }
    },
    "create_tab": { "type": "boolean" },
    "tab_input": {
      "type": "object",
      "properties": {
        "icon": { "type": "string" },
        "label": { "type": "string" },
        "order": { "type": "integer" }
      },
      "required": ["icon", "label", "order"]
    },
    "create_view": { "type": "boolean" },
    "view_input": {
      "type": "object",
      "properties": {
        "name": { "type": "string" },
        "description": { "type": "string" },
        "view_fields" : {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "field_name": { "type": "string" },
              "order": { "type": "integer" },
              "visible": { "type": "boolean" }
            },
            "required": ["field_name", "order", "visible"]
          }
        }
      },
      "required": ["name"]
    }
  },
  "required": ["name", "label"]
}

=== Manjunath-Aloji/mercury-scripts/models/01-user.model.json
{
    "$schema": "./01-model.schema.json",
    "name": "User",
    "label": "User",
    "description": "User model",
    "fields": [
        {
            "name": "first_name",
            "label": "first_name",
            "type": "string",
            "required": true
        },
        {
            "name": "last_name",
            "label": "last_name",
            "type": "string",
            "required": true
        },
        {
            "name": "user_name",
            "label": "user_name",
            "type": "string",
            "required": true
        },
        {
            "name": "phone",
            "label": "phone",
            "type": "string"
        },
        {
            "name": "email",
            "label": "email",
            "type": "string",
            "required": true
        },
        {
            "name": "password",
            "label": "password",
            "type": "string",
            "required": true
        },
        {
            "name": "role",
            "label": "role",
            "type": "enum",
            "enumType": "string",
            "enumValues": ["SUPER_ADMIN", "ADMIN", "STAFF", "STUDENT", "PARENT", "WARDEN"],
            "required": true
        },
        {
            "name": "gender",
            "label": "gender",
            "type": "enum",
            "enumType": "string",
            "enumValues": ["MALE", "FEMALE", "OTHER"],
            "required": true
        },
        {
            "name": "is_active",
            "label": "is_active",
            "type": "boolean"
        },
        {
            "name" : "avatar",
            "label" : "avatar",
            "type" : "relationship",
            "ref" : "Upload_File"
        },
        {
            "name" : "address",
            "label" : "address",
            "type" : "relationship",
            "ref" : "Address"
        }
    ],
    "create_tab": true,
    "tab_input": {
        "icon": "ShieldUser",
        "label": "User",
        "order": 1
    },
    "create_view": true,
    "view_input": {
        "name": "User View",
        "description": "User model View",
        "view_fields": [
            {"field_name": "first_name", "order": 1, "visible": true},
            {"field_name": "last_name", "order": 2, "visible": true},
            {"field_name": "user_name", "order": 3, "visible": true},
            {"field_name": "phone", "order": 4, "visible": true},
            {"field_name": "email", "order": 5, "visible": true},
            {"field_name": "role", "order": 6, "visible": true}
        ]
    }
}

=== Manjunath-Aloji/mercury-scripts/models/03-file.model.json
{
    "$schema": "./01-model.schema.json",
    "name": "Upload_File",
    "label": "Upload_File",
    "description": "File model",
    "fields": [
        {
            "name": "file_name",
            "label": "file_name",
            "type": "string",
            "required": true
        },
        {
            "name": "description",
            "label": "description",
            "type": "string"
        },
        {
            "name": "file_type",
            "label": "file_type",
            "type": "string",
            "required": true
        },
        {
            "name": "size",
            "label": "size",
            "type": "number"
        },
        {
            "name": "url",
            "label": "url",
            "type": "string"
        }
    ]
}

=== Manjunath-Aloji/mercury-scripts/models/04-admin.model.json
{
    "$schema": "./01-model.schema.json",
    "name": "Admin",
    "label": "Admin",
    "description": "Admin model",
    "fields": [
        {
            "name": "user",
            "type": "relationship",
            "label": "User",
            "ref": "User",
            "required": true
        },
        {
            "name": "institute",
            "type": "relationship",
            "label": "Institute",
            "ref": "Institute",
            "required": true
        }
    ],
    "create_tab": true,
    "tab_input": {
        "label": "Admin",
        "icon": "UserLock",
        "order": 3
    },
    "create_view": true,
    "view_input": {
        "name": "Admin View",
        "description": "Admin model View",
        "view_fields": [
            {
                "field_name": "user",
                "visible": true,
                "order": 1
            },
            {
                "field_name": "institute",
                "order": 2,
                "visible": true
            }
        ]
    }
    
}

=== Manjunath-Aloji/mercury-scripts/models/05-institute.model.json
{
    "$schema": "./01-model.schema.json",
    "name": "Institute",
    "label": "Institute",
    "description": "Institute model",
    "fields": [
        {
            "name": "name",
            "label": "name",
            "type": "string"
        },
        {
            "name": "description",
            "label": "description",
            "type": "string"
        },
        {
            "name": "address",
            "label": "address",
            "type": "relationship",
            "ref": "Address"
        },
        {
            "name": "principal",
            "label": "principal",
            "type": "relationship",
            "ref": "User"
        },
        {
            "name": "years_of_excellence",
            "label": "years_of_excellence",
            "type": "number"
        },
        {
            "name": "mobile",
            "label": "mobile",
            "type": "string"
        },
        {
            "name": "phone",
            "label": "phone",
            "type": "string"
        },
        {
            "name": "email",
            "label": "email",
            "type": "string"
        },
        {
            "name": "website",
            "label": "website",
            "type": "string"
        },
        {
            "name": "logo",
            "label": "logo",
            "type": "relationship",
            "ref": "Upload_File"
        },
        {
            "name": "banner",
            "label": "banner",
            "type": "relationship",
            "ref": "Upload_File"
        },
        {
            "name": "principal_sign",
            "label": "principal_sign",
            "type": "relationship",
            "ref": "Upload_File"
        },
        {
            "name": "is_active",
            "label": "is_active",
            "type": "boolean"
        }
    ],
    "create_tab": true,
    "tab_input": {
        "icon": "Landmark",
        "label": "Institute",
        "order": 4
    },
    "create_view": true,
    "view_input": {
        "name": "Institute View",
        "description": "Institute model View",
        "view_fields": [
            {
                "field_name": "name",
                "order": 1,
                "visible": true
            },
            {
                "field_name": "description",
                "order": 2,
                "visible": true
            },
            {
                "field_name": "address",
                "order": 3,
                "visible": true
            },
            {
                "field_name": "principal",
                "order": 4,
                "visible": true
            },
            {
                "field_name": "years_of_excellence",
                "order": 5,
                "visible": true
            },
            {
                "field_name": "mobile",
                "order": 6,
                "visible": true
            },
            {
                "field_name": "phone",
                "order": 7,
                "visible": true
            },
            {
                "field_name": "email",
                "order": 8,
                "visible": true
            },
            {
                "field_name": "website",
                "order": 9,
                "visible": true
            }
        ]
    }
}

=== Manjunath-Aloji/mercury-scripts/institute-model.json
{
  "$schema": "./model.schema.json",
  "name": "Institute",
  "label": "Institute",
  "description": "Institute model",
  "fields": [
    {
      "name": "name",
      "label": "name",
      "type": "string"
    },
    {
      "name": "website",
      "label": "website",
      "type": "string"
    }
  ],
  "create_tab": true,
  "tab_input": {
    "icon": "fa-solid fa-building",
    "label": "Institute",
    "order": 1
  },
  "create_view": true,
  "view_input": {
    "name": "Institute",
    "description": "Institute model View",
    "view_fields": [
        {
            "field_name": "name",
            "order": 1,
            "visible": true
        },
        {
            "field_name": "website",
            "order": 2,
            "visible": true
        }
    ]
  }
}

=== Manjunath-Aloji/mercury-scripts/models/02-address.model.json
{
    "$schema": "./01-model.schema.json",
    "name": "Address",
    "label": "Address",
    "description": "Address model",
    "fields": [
        {
            "name": "address",
            "label": "address",
            "type": "string"
        },
        {
            "name": "city",
            "label": "city",
            "type": "string"
        },
        {
            "name": "state",
            "label": "state",
            "type": "string"
        },
        {
            "name": "country",
            "label": "country",
            "type": "string"
        },
        {
            "name": "zip_code",
            "label": "zip_code",
            "type": "string"
        }
    ],
    "create_tab": true,
    "tab_input": {
        "icon": "MapPinHouse",
        "label": "Address",
        "order": 2
    },
    "create_view": true,
    "view_input": {
        "name": "Address View",
        "description": "Address model View",
        "view_fields": [
            {
                "field_name": "address",
                "order": 1,
                "visible": true
            },
            {
                "field_name": "city",
                "order": 2,
                "visible": true
            },
            {
                "field_name": "state",
                "order": 3,
                "visible": true
            },
            {
                "field_name": "country",
                "order": 4,
                "visible": true
            },
            {
                "field_name": "zip_code",
                "order": 5,
                "visible": true
            }
        ]
    }
}
